//! Static reference of color name variants per LDraw color code.
//!
//! The RON file (`color_names.ron`) is included into the binary at compile
//! time via [`include_str!`] and parsed lazily on first access. Two
//! consumers:
//!
//! - [`Palette::load`](crate::colors::palette::Palette::load) merges the
//!   name variants onto each [`PaletteColor`](crate::colors::PaletteColor),
//!   so the runtime can show alternate names and search across all of them.
//! - The catalog builder uses [`ColorReference::ldraw_code_for_rb`] to
//!   translate Rebrickable color ids (in `elements.csv` /
//!   `inventory_parts.csv`) into LDraw `ColorId`s before writing the
//!   bundled metadata DB.
//!
//! The reference itself is refreshed via the builder's `refresh-color-names`
//! subcommand — a rare, explicit, API-using path. The committed RON file is
//! the routine build's only color input.
//!
//! The RON file enables the `implicit_some` extension so present name fields
//! can be written as bare strings (`bricklink: "Red"`) rather than
//! `Some("Red")`; absent fields are simply omitted and deserialize to
//! `None`.

use std::collections::BTreeMap;
use std::sync::OnceLock;

use serde::Deserialize;

// Vendored from blockstar-core `src/colors/color_reference.rs` (plus the
// `ColorNames` struct from `palette.rs`) for the builder migration
// (bkfunk/brickdata#3); kept item-for-item compatible.

/// Alternate names for one color across the naming systems Rebrickable
/// tracks. All fields come from the static color reference
/// (`color_names.ron`), regenerated by the `refresh-color-names`
/// subcommand from `data/rebrickable/colors.json`.
#[derive(Debug, Clone, Default, PartialEq, Eq, serde::Serialize, Deserialize)]
pub struct ColorNames {
    pub lego: Option<String>,
    pub bricklink: Option<String>,
    pub rebrickable: Option<String>,
    /// All other name strings Rebrickable knows for this color, across any
    /// system (deduplicated, sorted). Populated for search; not used for
    /// display. Empty when no aliases exist.
    #[serde(default)]
    pub aliases: Vec<String>,
}

/// One row of the color reference table.
#[derive(Debug, Clone, Deserialize)]
pub struct ColorRefEntry {
    pub ldraw_code: u32,
    /// Rebrickable color id; `None` when this LDraw color has no Rebrickable
    /// equivalent.
    #[serde(default)]
    pub rb_color_id: Option<u32>,
    #[serde(default)]
    pub names: ColorNames,
}

/// The full color name reference, keyed by both LDraw code and Rebrickable id.
#[derive(Debug)]
pub struct ColorReference {
    by_ldraw: BTreeMap<u32, ColorRefEntry>,
    by_rb: BTreeMap<u32, u32>,
}

impl ColorReference {
    /// Look up an entry by LDraw color code.
    pub fn by_ldraw_code(&self, code: u32) -> Option<&ColorRefEntry> {
        self.by_ldraw.get(&code)
    }

    /// Translate a Rebrickable color id to an LDraw color code.
    pub fn ldraw_code_for_rb(&self, rb_id: u32) -> Option<u32> {
        self.by_rb.get(&rb_id).copied()
    }

    /// Iterate all entries, ordered by LDraw color code.
    pub fn entries(&self) -> impl Iterator<Item = &ColorRefEntry> {
        self.by_ldraw.values()
    }

    /// Number of entries in the reference.
    pub fn len(&self) -> usize {
        self.by_ldraw.len()
    }

    /// Whether the reference has any entries.
    pub fn is_empty(&self) -> bool {
        self.by_ldraw.is_empty()
    }

    fn from_entries(entries: Vec<ColorRefEntry>) -> Self {
        let mut by_ldraw: BTreeMap<u32, ColorRefEntry> = BTreeMap::new();
        let mut by_rb: BTreeMap<u32, u32> = BTreeMap::new();
        for entry in entries {
            let code = entry.ldraw_code;
            if let Some(rb) = entry.rb_color_id {
                if let Some(prior_code) = by_rb.insert(rb, code) {
                    panic!(
                        "color_names.ron: rb_color_id {rb} maps to both ldraw_code \
                         {prior_code} and {code}"
                    );
                }
            }
            if by_ldraw.insert(code, entry).is_some() {
                panic!("color_names.ron: ldraw_code {code} appears more than once");
            }
        }
        Self { by_ldraw, by_rb }
    }
}

/// Get the static color reference, parsed lazily from the bundled RON file.
pub fn color_reference() -> &'static ColorReference {
    static REF: OnceLock<ColorReference> = OnceLock::new();
    REF.get_or_init(|| {
        let entries: Vec<ColorRefEntry> = ron::from_str(include_str!("color_names.ron"))
            .expect("color_names.ron should parse — included at compile time");
        ColorReference::from_entries(entries)
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reference_loads_starter_entries() {
        let r = color_reference();
        assert!(!r.is_empty());
        assert!(r.by_ldraw_code(4).is_some(), "ldraw 4 (Red) missing");
        assert_eq!(r.ldraw_code_for_rb(4), Some(4));
    }

    #[test]
    fn red_has_canonical_names_across_systems() {
        let red = color_reference().by_ldraw_code(4).expect("red");
        assert_eq!(red.names.lego.as_deref(), Some("Bright red"));
        assert_eq!(red.names.bricklink.as_deref(), Some("Red"));
        assert_eq!(red.names.rebrickable.as_deref(), Some("Red"));
    }
}
